# Generated by Django 5.2.17 on 2026-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
