# Generated by Django 6.1 on 2026-08-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_updated_at_idx',
        ),
    ]
