# Generated by Django 5.2.17 on 2026-09-04 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('input_volume_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('output_volume_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_type', models.CharField(choices=[('COAGULANT', 'Coagulant Solution'), ('FLOCCULANT', 'Flocculant Solution')], max_length=20)),
                ('quantity_ml', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosing_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosing_records', to='treatment_process.treatmentbatch')),
            ],
        ),
        migrations.AddField(
            model_name='treatmentbatch',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='treatment_process.treatmentprocess'),
        ),
        migrations.CreateModel(
            name='TreatmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('WASTEWATER_COLLECTION', 'Wastewater Collection'), ('TREATMENT', 'Treatment'), ('COAGULATION', 'Coagulation'), ('COAGULATION_MIXING', 'Coagulation Mixing'), ('COAGULATION_REST', 'Coagulation Rest'), ('FLOCCULATION', 'Flocculation'), ('FILTER_SCREENING', 'Filter / Screening'), ('AERATION', 'Aeration')], max_length=40)),
                ('sequence', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Process duration in seconds')),
                ('target_volume_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='treatment_process.treatmentprocess')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='treatmentbatch',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_batches', to='treatment_process.treatmentstage'),
        ),
        migrations.CreateModel(
            name='ProcessExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='treatment_process.treatmentbatch')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='treatment_process.treatmentstage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='treatmentstage',
            constraint=models.UniqueConstraint(fields=('process', 'sequence'), name='unique_process_stage_sequence'),
        ),
    ]
