# Generated by Django 5.2.17 on 2026-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('treatment_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentstage',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='treatment_stages', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='treatmentstage',
            name='stage_type',
            field=models.CharField(choices=[('WASTEWATER_COLLECTION', 'Wastewater Collection'), ('NORMALWATER_COLLECTION', 'NormalWater Collection'), ('TREATMENT', 'Treatment'), ('COAGULATION', 'Coagulation'), ('FLOCCULATION', 'Flocculation'), ('FILTER_SCREENING', 'Filter / Screening'), ('AERATION', 'Aeration')], max_length=40),
        ),
    ]
