# Generated by Django 5.2.17 on 2026-09-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_process', '0002_treatmentstage_equipments_and_more'),
        ('users', '0004_user_reset_otp_user_reset_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentstage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treatmentstage', to='users.user'),
            preserve_default=False,
        ),
    ]
