# Generated by Django 5.2.17 on 2026-09-05 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_user'),
        ('treatment_process', '0003_treatmentstage_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stage_execution_logs',
                'ordering': ['stage__sequence'],
            },
        ),
        migrations.AlterModelOptions(
            name='processexecutionlog',
            options={'ordering': ['process__stage__sequence', 'process__sequence']},
        ),
        migrations.RemoveIndex(
            model_name='treatmentprocess',
            name='treatment_process_status_idx',
        ),
        migrations.RemoveField(
            model_name='treatmentbatch',
            name='process',
        ),
        migrations.RemoveField(
            model_name='treatmentprocess',
            name='status',
        ),
        migrations.AddField(
            model_name='processexecutionlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processexecutionlog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_execution_logs', to='treatment_process.treatmentbatch'),
        ),
        migrations.AlterField(
            model_name='processexecutionlog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='treatmentprocess',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Expected process duration in seconds'),
        ),
        migrations.AlterField(
            model_name='treatmentstage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='processexecutionlog',
            index=models.Index(fields=['batch', 'process'], name='process_exec_batch_process_idx'),
        ),
        migrations.AddIndex(
            model_name='processexecutionlog',
            index=models.Index(fields=['status'], name='process_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentprocess',
            index=models.Index(fields=['is_active'], name='treatment_process_active_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentstage',
            index=models.Index(fields=['stage_type'], name='treatment_stage_type_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentstage',
            index=models.Index(fields=['user'], name='treatment_stage_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='processexecutionlog',
            constraint=models.UniqueConstraint(fields=('batch', 'process'), name='unique_batch_process_execution'),
        ),
        migrations.AddConstraint(
            model_name='treatmentstage',
            constraint=models.UniqueConstraint(fields=('user', 'sequence'), name='unique_user_stage_sequence'),
        ),
        migrations.AlterModelTable(
            name='processexecutionlog',
            table='process_execution_logs',
        ),
        migrations.AddField(
            model_name='stageexecutionlog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_execution_logs', to='treatment_process.treatmentbatch'),
        ),
        migrations.AddField(
            model_name='stageexecutionlog',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='treatment_process.treatmentstage'),
        ),
        migrations.AddIndex(
            model_name='stageexecutionlog',
            index=models.Index(fields=['batch', 'stage'], name='stage_exec_batch_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='stageexecutionlog',
            index=models.Index(fields=['status'], name='stage_exec_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stageexecutionlog',
            constraint=models.UniqueConstraint(fields=('batch', 'stage'), name='unique_batch_stage_execution'),
        ),
    ]
