# Generated by Django 5.2.17 on 2026-09-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_current_state'),
        ('treatment_process', '0004_stageexecutionlog_alter_processexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentprocess',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='treatment_processes', to='equipment.equipment'),
        ),
        migrations.CreateModel(
            name='StageBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_batches', to='treatment_process.treatmentstage')),
            ],
            options={
                'db_table': 'stage_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageBatchProcessExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_seconds', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_batch_executions', to='treatment_process.treatmentprocess')),
                ('stage_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_executions', to='treatment_process.stagebatch')),
            ],
            options={
                'db_table': 'stage_batch_process_executions',
                'ordering': ['stage_batch__created_at', 'process__sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='stagebatch',
            index=models.Index(fields=['stage', 'status'], name='stage_batch_stage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stagebatch',
            index=models.Index(fields=['status'], name='stage_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stagebatchprocessexecution',
            index=models.Index(fields=['stage_batch', 'process'], name='stage_batch_process_idx'),
        ),
        migrations.AddIndex(
            model_name='stagebatchprocessexecution',
            index=models.Index(fields=['status'], name='stage_batch_process_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagebatchprocessexecution',
            constraint=models.UniqueConstraint(fields=('stage_batch', 'process'), name='unique_stage_batch_process_execution'),
        ),
    ]
