# Generated by Django 5.2.17 on 2026-09-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_current_state'),
        ('treatment_process', '0005_treatmentprocess_equipments_stagebatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageBatchProcessEquipmentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('ON', 'On'), ('OFF', 'Off')], max_length=10, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_batch_process_equipment_executions', to='equipment.equipment')),
                ('stage_batch_process_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_executions', to='treatment_process.stagebatchprocessexecution')),
            ],
            options={
                'db_table': 'stage_batch_process_equipment_executions',
                'ordering': ['stage_batch_process_execution__process__sequence', 'equipment__name'],
                'indexes': [models.Index(fields=['stage_batch_process_execution', 'equipment'], name='stage_process_equipment_idx'), models.Index(fields=['equipment'], name='stage_equipment_idx'), models.Index(fields=['state'], name='stage_process_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('stage_batch_process_execution', 'equipment'), name='unique_process_equipment_execution')],
            },
        ),
    ]
