# Generated by Django 5.2.17 on 2026-09-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_merge_20260907_0524'),
        ('treatment_process', '0006_stagebatchprocessequipmentexecution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagebatchprocessequipmentexecution',
            options={'ordering': ['stage_batch_process_execution__process__sequence', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='stagebatchprocessequipmentexecution',
            name='unique_process_equipment_execution',
        ),
        migrations.RemoveIndex(
            model_name='stagebatchprocessequipmentexecution',
            name='stage_process_equipment_idx',
        ),
        migrations.RemoveIndex(
            model_name='stagebatchprocessequipmentexecution',
            name='stage_equipment_idx',
        ),
        migrations.RemoveIndex(
            model_name='stagebatchprocessequipmentexecution',
            name='stage_process_state_idx',
        ),
        migrations.AddField(
            model_name='stagebatchprocessequipmentexecution',
            name='actual_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stagebatchprocessequipmentexecution',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagebatchprocessequipmentexecution',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Time at which the next equipment operation should happen.', null=True),
        ),
        migrations.AddField(
            model_name='stagebatchprocessequipmentexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stagebatchprocessequipmentexecution',
            index=models.Index(fields=['status', 'scheduled_at'], name='equipment_exec_due_idx'),
        ),
        migrations.AddIndex(
            model_name='stagebatchprocessequipmentexecution',
            index=models.Index(fields=['stage_batch_process_execution'], name='equipment_exec_process_idx'),
        ),
    ]
