# Generated by Django 5.2.17 on 2026-09-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_merge_20260907_0524'),
        ('treatment_process', '0007_alter_stagebatchprocessequipmentexecution_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageEquipmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('current_state', models.CharField(choices=[('OFF', 'Off'), ('ON', 'On')], default='OFF', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('FAULT', 'Fault')], default='ACTIVE', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_configurations', to='equipment.equipment')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_configurations', to='treatment_process.treatmentstage')),
            ],
            options={
                'db_table': 'stage_equipment_configs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['stage', 'equipment'], name='stage_equipment_config_idx'), models.Index(fields=['stage', 'is_active'], name='stage_equipment_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('stage', 'equipment'), name='unique_stage_equipment_config')],
            },
        ),
    ]
