# Generated by Django 5.2.17 on 2026-09-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_process', '0008_stageequipmentconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentstage',
            name='stage_type',
            field=models.CharField(choices=[('INLET', 'Inlet'), ('TREATMENT', 'Treatment'), ('COAGULATION', 'Coagulation'), ('FLOCCULATION', 'Flocculation'), ('FILTER_SCREENING', 'Filter / Screening'), ('AERATION', 'Aeration')], max_length=40),
        ),
    ]
