# Generated by Django 5.2.17 on 2026-09-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_process', '0009_alter_treatmentstage_stage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageequipmentconfig',
            name='status',
        ),
    ]
