# Generated by Django 5.2.17 on 2026-09-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_process', '0010_remove_stageequipmentconfig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageequipmentconfig',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('FAULT', 'Fault')], default='ACTIVE', max_length=20),
        ),
    ]
