# Generated by Django 5.2.17 on 2026-09-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_process', '0011_stageequipmentconfig_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageequipmentconfig',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='stageequipmentconfig',
            name='start_time',
        ),
    ]
