# Generated by Django 5.2.17 on 2026-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_remove_equipment_equipment_status_idx_and_more'),
        ('treatment_process', '0011_stageequipmentconfig_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stagebatchprocessequipmentexecution',
            constraint=models.UniqueConstraint(fields=('stage_batch_process_execution', 'equipment'), name='unique_process_equipment_execution'),
        ),
    ]
