# Generated by Django 5.2.17 on 2026-09-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_process', '0012_remove_stageequipmentconfig_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageequipmentconfig',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageequipmentconfig',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
