# Generated by Django 5.2.17 on 2026-09-04 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('users', '0004_user_reset_otp_user_reset_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='users.user'),
            preserve_default=False,
        ),
    ]
