# Generated by Django 5.2.17 on 2026-09-05 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_user'),
        ('treatment_process', '0004_stageexecutionlog_alter_processexecutionlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentManualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_logs', to='equipment.equipment')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_manual_logs', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_manual_logs', to='treatment_process.treatmentstage')),
            ],
            options={
                'db_table': 'equipment_manual_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['equipment', 'started_at'], name='equipment_manual_log_idx'), models.Index(fields=['stage', 'started_at'], name='stage_manual_log_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TESTING', 'Testing'), ('COMPLETED', 'Completed'), ('MERGED', 'Merged'), ('CANCELLED', 'Cancelled')], default='TESTING', max_length=20)),
                ('is_merged', models.BooleanField(default=False)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='equipment.equipment')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_equipment_tests', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_tests', to='treatment_process.treatmentstage')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'equipment_tests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'stage'], name='equipment_test_stage_idx'), models.Index(fields=['status'], name='equipment_test_status_idx')],
            },
        ),
    ]
