# Generated by Django 5.2.17 on 2026-09-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_duration_seconds_equipment_end_time_and_more'),
        ('treatment_process', '0004_stageexecutionlog_alter_processexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmanuallog',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_manual_logs', to='treatment_process.treatmentstage'),
        ),
    ]
