# Generated by Django 5.2.17 on 2026-09-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_duration_seconds_equipment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_state',
            field=models.CharField(choices=[('OFF', 'Off'), ('ON', 'On')], default='OFF', max_length=10),
        ),
    ]
