# Generated by Django 5.2.17 on 2026-09-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipmentmanuallog_stage'),
        ('equipment', '0004_equipment_current_state'),
    ]

    operations = [
    ]
