# Generated by Django 5.2.17 on 2026-09-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_merge_20260907_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='current_state',
        ),
    ]
