# Generated by Django 5.2.17 on 2026-09-12 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipment_current_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipment',
            name='equipment_status_idx',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='status',
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['is_active'], name='equipment_is_active_idx'),
        ),
    ]
