# Generated by Django 5.2.17 on 2026-09-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'process_parameters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('IDLE', 'Idle'), ('FAULT', 'Fault'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='equipment.equipment')),
            ],
            options={
                'db_table': 'equipment_statuses',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['equipment', 'recorded_at'], name='equip_status_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('SENSOR', 'Sensor'), ('MANUAL', 'Manual')], default='SENSOR', max_length=20)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_readings', to='equipment.equipment')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='process_monitoring.processparameter')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_readings', to='sensors.sensor')),
            ],
            options={
                'db_table': 'process_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['parameter', 'recorded_at'], name='proc_param_date_idx'), models.Index(fields=['equipment', 'recorded_at'], name='proc_equip_date_idx'), models.Index(fields=['sensor', 'recorded_at'], name='proc_sensor_date_idx')],
            },
        ),
    ]
