# Generated by Django 5.2.17 on 2026-08-25 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sensor_types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='sensor_type_code_idx'), models.Index(fields=['is_active'], name='sensor_type_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, max_length=150, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('FAULT', 'Fault')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='equipment.equipment')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensors.sensortype')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(default='MANUAL', help_text='Example: MANUAL, MQTT, API', max_length=50)),
                ('raw_value', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['sensor', 'recorded_at'], name='sensor_reading_idx'), models.Index(fields=['recorded_at'], name='reading_recorded_idx'), models.Index(fields=['status'], name='reading_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['code'], name='sensor_code_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['equipment'], name='sensor_equipment_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['status'], name='sensor_status_idx'),
        ),
    ]
