# Generated by Django 5.2.17 on 2026-08-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'water_quality_parameters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('SENSOR', 'Sensor'), ('LAB', 'Laboratory'), ('MANUAL', 'Manual')], default='SENSOR', max_length=20)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='water_quality.waterqualityparameter')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_readings', to='plants.plant')),
                ('plant_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_quality_readings', to='plants.plantstage')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_quality_readings', to='sensors.sensor')),
            ],
            options={
                'db_table': 'water_quality_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['plant', 'recorded_at'], name='wq_plant_date_idx'), models.Index(fields=['parameter', 'recorded_at'], name='wq_param_date_idx'), models.Index(fields=['sensor', 'recorded_at'], name='wq_sensor_date_idx')],
            },
        ),
    ]
